### ISSUE TITLE
can not run

### ISSUE THREAD

**Issue by veecam** [oprypin/sixcells#5]
This application failed to start because it could not find or load the Qt platform plugin “windows”

windows 10

**Comment by oprypin** [comment]
You can use an older version from the Releases page

**Comment by oprypin** [comment]
Did that help?

**Comment by oprypin** [comment]
I meant version 2.4.**0** or earlier.

But anyway, I cannot reproduce this problem. Make sure that all files are extracted properly.

**Comment by oprypin** [comment]
Welp, no reply &rarr; nothing actionable
